// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'gohomebtn': string;
  'homeicon': string;
}
declare const cssExports: CssExports;
export = cssExports;
