// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'comment': string;
  'commentbox': string;
  'comments': string;
  'commentscontainer': string;
  'commentuserdetails': string;
}
declare const cssExports: CssExports;
export = cssExports;
