// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cardcontainer': string;
  'tagheader': string;
  'tagheading': string;
  'tagquestion': string;
}
declare const cssExports: CssExports;
export = cssExports;
