// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'boxStyle': string;
  'mainDiv': string;
  'title': string;
}
declare const cssExports: CssExports;
export = cssExports;
