// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btntext': string;
  'button': string;
  'buttonStyling': string;
}
declare const cssExports: CssExports;
export = cssExports;
