// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'sectioncontainer': string;
}
declare const cssExports: CssExports;
export = cssExports;
