// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'invalid': string;
  'votingcontainer': string;
}
declare const cssExports: CssExports;
export = cssExports;
