// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'answerbox': string;
  'answerform': string;
  'answerformcontainer': string;
  'askedview': string;
  'details': string;
  'header': string;
  'postbtn': string;
  'question': string;
  'questiondetail': string;
  'questiondetails': string;
  'questionheading': string;
  'questionvoting': string;
  'tag': string;
  'tagbox': string;
  'user': string;
  'view': string;
}
declare const cssExports: CssExports;
export = cssExports;
