// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activeitem': string;
  'menuitem': string;
}
declare const cssExports: CssExports;
export = cssExports;
