// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'answers': string;
  'asked': string;
  'askquestionbutton': string;
  'home': string;
  'homecard': string;
  'homecardcontainer': string;
  'homecarddetails': string;
  'homecardleft': string;
  'homecardright': string;
  'numofque': string;
  'questiondetails': string;
  'questionhead': string;
  'questionheading': string;
  'questionsheadline': string;
  'tag': string;
  'tagbox': string;
  'tagscontainer': string;
  'views': string;
  'votes': string;
}
declare const cssExports: CssExports;
export = cssExports;
