// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'answerheader': string;
  'answers': string;
  'answersbody': string;
  'answerscontainer': string;
  'answeruser': string;
  'answervoting': string;
  'asked': string;
}
declare const cssExports: CssExports;
export = cssExports;
