// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'tag': string;
  'tagcard': string;
  'tagcardcontainer': string;
  'tagcarddetails': string;
  'tagdetails': string;
  'tagheading': string;
  'tagsub': string;
  'tagsubleft': string;
  'tagsubright': string;
}
declare const cssExports: CssExports;
export = cssExports;
