// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'headercenter': string;
  'headerleft': string;
  'headerright': string;
  'logotext': string;
  'tagStyling': string;
}
declare const cssExports: CssExports;
export = cssExports;
