// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'nextBttn': string;
  'paginationActive': string;
  'paginationBttns': string;
  'paginationDisabled': string;
  'previousBttn': string;
}
declare const cssExports: CssExports;
export = cssExports;
